### ISSUE TITLE
login 14504 error

### ISSUE THREAD

**Issue by flyingman99** [blizzless/blizzless-diiis#119]
cannot login, how to resolve the problem？

![D3LoginError](https://user-images.githubusercontent.com/36907084/216549883-2249142e-05d5-4489-b328-4d49959924e4.png)

![D3LoginError1](https://user-images.githubusercontent.com/36907084/216549931-c26df333-e5c5-448d-b037-47d95d9a3cef.png)

**Comment by iamdroppy** [comment]
I am uncertain as to the cause of this error code. Could it be due to a lack of installation of the battlenet.p12?

Please ensure that you have completed the preparation steps outlined in the Blizzless-DIIIS repository prior to proceeding.: https://github.com/blizzless/blizzless-diiis#prepare-client
