### ISSUE TITLE
Permission denied exception

### ISSUE THREAD

**Issue by goremykin** [blizzless/blizzless-diiis#120]
The app crashes on linux when we try to bind port 80 as any port < 1024 requires root.
Did we use another port before?

**Comment by iamdroppy** [comment]
~~If you run as super user, you will quickly make it work!~~

Just kidding - the default one is 8081 in code, the config.ini is as 80 👍 

We have set the port to 80 in order to allow for communication with Battle.net without needing to apply binary patches besides the protocol change (https to http). This enables us to connect to www.battle.net and utilize our "REST module" in order to simulate responses of data. With the community's approval, we should be transitioning to ASP.NET.  Just not an emergency right now - we have some other issues to tackle - some that have appeared post 2023 builds... Sorry if it passed through.

**Comment by goremykin** [comment]
@iamdroppy, I am still don't fully understand the problem as I am not in the context...
Can we discuss this somewhere? I would like to know more

**Comment by iamdroppy** [comment]
@goremykin Surely, over discord: Droppy#5264

Basically, check your `config.ini` file (default is https://github.com/blizzless/blizzless-diiis/blob/community/configs/config.ini )

**Comment by goremykin** [comment]
@iamdroppy, Could you accept the request from goremykin$1997? :)

**Comment by iamdroppy** [comment]
sent you a request, haven't received it
